import {default as Billing} from "./Billing"
import {default as Business} from "./Business"
import {default as Buttons} from "./Buttons"
import {default as CardDeal} from "./CardDeal"
import {default as Clients} from "./Clients"
import {default as CTA} from "./CTA"
import {default as FeedbackCard} from "./FeedbackCard"
import {default as Footer} from "./Footer"
import {default as Navbar} from "./Navbar"
import {default as GetStarted} from "./GetStarted"
import {default as Hero} from "./Hero"
import {default as Stats} from "./Stats"
import {default as Testimonial} from "./Testimonial"

export {Billing, Business, Buttons, CardDeal, Clients, CTA, FeedbackCard, Footer, Navbar, Hero, GetStarted, Stats, Testimonial};